#from .player_bidding_strategy import PlayerBiddingStrategy as PlayerBiddingStrategy
#from .iql_bidding_strategy import IqlBiddingStrategy as PlayerBiddingStrategy
# from .bc_bidding_strategy import BcBiddingStrategy as PlayerBiddingStrategy
# from .onlinelp_bidding_strategy import OnlineLpBiddingStrategy as PlayerBiddingStrategy
#from .edac_bidding_strategy import EdacBiddingStrategy as PlayerBiddingStrategy
from .cql_bidding_strategy import CQLBiddingStrategy as PlayerBiddingStrategy